name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      IMAGE_URL: ""
      APP_SERVER: ${{ secrets.APP_SERVER }}
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_TOKEN: ${{ secrets.APP_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preset Image Name
        id: set_image_url
        run: |
          IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: ${{ steps.set_image_url.outputs.image_url }}

      - name: Deploy Image to Server
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ env.APP_SERVER }}
          app: ${{ env.APP_NAME }}
          token: ${{ env.APP_TOKEN }}
          image: ${{ steps.set_image_url.outputs.image_url }}